### PR TITLE
Fix missing template error on CentOS 8

### PR DESCRIPTION
**Pull request by blackknight36**
This change fixes the error that occurs when puppet runs.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'koji/hub/ssl.conf.CentOS.8.erb' (file: /etc/puppetlabs/code/environments/koji_c8/forge_modules/koji/manifests/httpd.pp, line: 32, column: 26) on node mdct-koji-c8.dartcontainer.com
```

I also removed the Fedora template since the ssl.conf file should be generic enough to work on any server that is running Apache.

### CODE REVIEW

**Comment by jflorian** [comment]
Thanks for this.  Would you mind testing the `feature_el8` branch I've pushed here?  It's similar, although:
* it has simpler module data because the work-around is no longer needed
* keeps the Hub's `ssl.conf` template unique to each OS release to preserve default protocol levels and other settings

I realize a single template can/will work, but I feel any deviation from the default as-shipped security settings needs explicit rationale provided with the commit.

**Comment by blackknight36** [comment]
I will test the feature_el8 branch on a CentOS 8 node.

**Comment by blackknight36** [comment]
The feature_el8 branch works on CentOS 8.  I am closing this PR since the other branch works.

**Comment by jflorian** [comment]
Thanks for testing this and catching my goof in the first place.

**Pull request closed without merging**
